### PR TITLE
Issue #10: Format bar (phone)

### PR DESCRIPTION
**Pull request by aforcier**
Addresses #10.
- Updated the format bar appearance to use the iOS assets and styling
- Implemented `bold`, `italic`, `blockquote`, `orderedList`, and `unorderedList` formatting
- Added `media`, `link` and `HTML` buttons (currently inactive), to be implemented in future PRs
- Format bar buttons (except `HTML`) scroll horizontally when needed
- Focusing on the title disables the format bar (except `HTML`)

2015-04-17-format-bar-preview-cropped-full

Some notes:
- There are a few bugs present:
  1. Android's autocorrect/autocomplete in some cases interferes when applying/removing formatting (`blockquote`/`ol`/`ul`) and causes bugginess (duplicating words mainly). This is an extension of issue #123.
  2. Blockquote behaves a bit strangely, with the same issues listed in https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/597, which will be fixed in #127.
- Possible animation for format bar buttons (and removal of the blue underline) sold separately (#131)

### CODE REVIEW

**Comment by aforcier** [comment]
Note that on small screens a format bar button can be partially hidden (in this example the orderedList icon is barely making into the visible part of the scrollable format bar):

format-bar-scroll

Should we treat this case differently? cc @thianhlu

**Comment by aforcier** [comment]
cc @bummytime

**Comment by bummytime** [comment]
@aforcier re: the clipped format bar above, if we tightened up the static HTML button on the right (make its width smaller), we would see more of that obscured link icon. 

That "HTML" text is from the iPad version...on the phone it looks a little different: https://cldup.com/p9IQoNoLwT.jpg

**Comment by aforcier** [comment]
@bummytime I don't see an asset for that here:

https://github.com/wordpress-mobile/WordPress-Editor-iOS/tree/develop/Assets

Is it a text button on iPhone then?

**Comment by bummytime** [comment]
Yes. :-)

**Comment by bummytime** [comment]
Though we don't have to do the same thing on Android...

**Comment by aforcier** [comment]
Here's a pass at tightening up the HTML button:

format-bar-scroll-small-html

Comparison with earlier version:

format-bar-scroll-comparison

What do you think? cc @thianhlu

**Comment by thianhlu** [comment]
I like.

**Comment by aforcier** [comment]
Updated with shrunken HTML button. Slightly different from the above sample screenshots (I used text in those, while my last change and the screenshots below use an image resource).

Here's what the format bar looks like now on a Nexus 4 (left) and a Nexus One running ICS (right):

format-bar-scroll-small-html-nexusone-nexus4-comparison

(full Nexus4 screenshot: https://cloudup.com/cYEjCK0zfJ9)

**Comment by bummytime** [comment]
Looking good @aforcier !

Could we expand the scroll area to the left edge of the screen?

napkin 3 04-24-15 10 43 53 am

**Comment by bummytime** [comment]
@thianhlu More of a design question here. Looking at @aforcier's image cap from above:

screen shot 2015-04-24 at 10 48 26 am

It seems like we need some kind of graphical affordance to let the user know that the toolbar can scroll. Evernote achieves this by adding a material-like drop shadow to the static part of the toolbar on the right hand side:

screen

Not saying we have to do that, but I think we should do something...

**Comment by bummytime** [comment]
@aforcier ok. I chatted with @thianhlu offline and I will make a separate issue for the scrolling UX. So in terms of this PR, if you fix the left hand scroll padding I mentioned above, I would say :shipit:!

**Comment by aforcier** [comment]
Fixed left edge scroll issue:

format-bar-left-scroll-fix

**Comment by bummytime** [comment]
:shipit:

**Pull request merged**
