### PR TITLE
Issue #11: HTML mode

### PR DESCRIPTION
**Pull request by aforcier**
Addresses #11, adding HTML mode to the editor.

This PR omits styling of the HTML tags/entities - that work is nearing completion but will be added in a future PR for brevity (issue ref #177).

Points of interest:
- Toggle between visual/HTML using format bar button
- The title uses `Merriweather-Bold`, same as visual mode and the iOS editor' title field
- The content uses the Android default monospace font (`Roboto` for all the APIs we support) - iOS' `Menlo` font couldn't be used as it seems to be iOS-proprietary
- Small departure from iOS editor: made the list format bar buttons (`ol` and `ul`) also add `li` tags along with their normal tags: https://cloudup.com/cOxN-nUMajn

11-html-mode-nexus4

### CODE REVIEW

**Comment by aforcier** [comment]
cc @bummytime, @thianhlu, @meremagee

**Comment by aforcier** [comment]
Added some demo content to the initial post.

**Comment by thianhlu** [comment]
+1 for the changes

**Comment by bummytime** [comment]
@aforcier looks like we have a keyboard issue (prolly related to #165) when switching modes.

keyboard_down

Did you experience this during development?

**Comment by aforcier** [comment]
I'm able to repro that, looking into it.

**Comment by bummytime** [comment]
Ok @aforcier, first pass is done, nice work!  Besides those failing tests we chatted about offline and the keyboard issue above, I did not find much else wrong.

**Comment by aforcier** [comment]
- 'Fixed' the keyboard issue @bummytime found above. The keyboard now re-appears right after it drops when switching from visual -> HTML mode (it stays up when switching the other way, from HTML -> visual). Ideally it wouldn't drop at all - opened issue #178 for that
- Fixed an integration test that failed on some devices

Ready for another pass @bummytime!

**Comment by bummytime** [comment]
w00t! Integrations tests are working on my Nexus4 like a champ:

screen shot 2015-07-09 at 11 08 39 am

On my S6, not so much:

```
Tests on SM-G920T - 5.1.1 failed: Instrumentation run failed due to 'java.lang.IncompatibleClassChangeError'

com.android.builder.testing.ConnectedDevice > No tests found.[SM-G920T - 5.1.1] FAILED
No tests found. This usually means that your test classes are not in the form that your test runner expects (e.g. don't inherit from TestCase or lack @Test annotations).
:WordPressEditor:connectedAndroidTestDebug FAILED

FAILURE: Build failed with an exception.
```

_throws S6 in garbage_

**Comment by bummytime** [comment]
@aforcier With #178 created, I am :+1: with the fix you provided here to keep the keyboard up.

**Comment by aforcier** [comment]
Also found an issue with switching from visual -> HTML mode, when using a hardware keyboards on `API<19`. The `WebView` loses focus and you have to tap to edit it. Opening a separate issue for this (#179).

**Comment by bummytime** [comment]
@aforcier word. 2nd pass is done. :shipit: 

Really nice work on this!

**Pull request merged**
