### PR TITLE
Issue #383: Drop WordPress-Editor-Common

### PR DESCRIPTION
**Pull request by aforcier**
Addresses #383, getting rid of `libs/editor-common` in the editor, and moving the assets to the main project folder.

I also did some cleanup, moving all the libraries we shouldn't be modifying to a `libs/` folder inside `assets/`.

Note: we'll also need to update the WPAndroid README to delete the symlink instructions for Windows when this is merged.

cc @maxme

### CODE REVIEW

**Comment by maxme** [comment]
Lib dependency paths must be updated in `test-formatter.js` (eg. `require('../libs/underscore-min.js');` instead of `require('../underscore-min.js');` )

**Comment by maxme** [comment]
It's not a new thing, but now that I think of it, we should not have these `example` and `test` directories (and `node_modules` subdir) in the main `assets/` directory (everything in there will be packaged in the final apk).

`example` should be moved to the example project, and `test` could be moved in `WordPressEditor/src/test/js`

**Comment by aforcier** [comment]
> Lib dependency paths must be updated in test-formatter.js (eg. require('../libs/underscore-min.js'); instead of require('../underscore-min.js'); )

Oops, I was sure I had run the tests before pushing :( Fixed

> example should be moved to the example project, and test could be moved in WordPressEditor/src/test/js

Agreed, done in 7072c80 and c017777. I updated the README with new instructions (note that now you need to run `mocha test*` rather than just `mocha`, that allowed me to drop the `test/` subfolder (`test/js/test/` was getting too awkward).

Ready for another pass @maxme!

**Comment by maxme** [comment]
:shipit:

**Pull request merged**
