### PR TITLE
Issue #131: Animate format bar button clicks

### PR DESCRIPTION
**Pull request by aforcier**
Addresses #131, part of the #145 group of format bar changes.

Adds a ripple animation on click to the format bar buttons, reflecting the changes made to iOS here: https://github.com/wordpress-mobile/WordPress-Editor-iOS/pull/678

Demo: https://cloudup.com/csRulrliA6t

### CODE REVIEW

**Comment by aforcier** [comment]
cc @bummytime @thianhlu

**Comment by bummytime** [comment]
Tested on:
- API 16 :+1: 
- API 17 :+1:  (including Nexus4 device)
- API 18 :+1: 
- API 19 :+1: 
- API 21 :-1:  (See below)
- API 22 :+1:  (including Samsung S6 and Nexus 7 devices)

Unit tests: Green
Connected Tests: Green

So in Genymotion (new image) the animations are very slow on API 21. I realize this just could be a simulator-thing. Will post a vid shortly...

**Comment by bummytime** [comment]
Video of slow animation: https://cloudup.com/cmCO6qjWyST

**Comment by bummytime** [comment]
So a little more testing of API 21...looks like it is probably just a emulator/simulator thing. If I force GPU rendering in the stock API 21 emu, the animations work as expected (no frame drops). Might want to test this on an actual device, but I think we are ok.

**Comment by bummytime** [comment]
Code looks all good @aforcier. :shipit:

**Pull request merged**
