### PR TITLE
Issue #199: Format bar tweaks (phone)

### PR DESCRIPTION
**Pull request by aforcier**
Addresses #199.
- Dropped the `5dp` padding between format bar buttons in the phone layout
- Added a new layout for screens with at least `360dp` width (but smaller than a tablet)

For screens with width of at least `360dp`, the format bar doesn't scroll and the chevron is replaced with a vertical divider we had before. For the rest, the existing layout with scroll and chevron is used.

Note that a phone that displays the chevron layout in portait is still usually wide enough in landscape to show the non-chevron layout.

Nexus S (`< 360dp` width):

199-format-bar-nexuss

Nexus 5 (exactly `360dp` width):

199-format-bar-nexus5

cc @bummytime @thianhlu

### CODE REVIEW

**Comment by thianhlu** [comment]
:+1:

**Comment by bummytime** [comment]
@thianhlu Here is a picture of a Nexus 4 with the updated format bar layout:

screen

Are you ok with the left aligned icons? (referring to the gap after the link icon)

**Comment by bummytime** [comment]
FYI: Nexus 4 is 1280 x 768 px

**Comment by thianhlu** [comment]
What kind of effort would it take to calculate excess space and equally space around icons for all mobile phone layouts where gap is larger than 20dp?

**Comment by aforcier** [comment]
I'll look into it @thianhlu, should just be an extra layout.

**Comment by thianhlu** [comment]
and perhaps we cap the padding to 5dp per icon

**Comment by aforcier** [comment]
To summarize, these are the new layouts to come out of this:

`<360dp`: scrolling format bar with chevron
`360dp`-`380dp`: left-aligned format bar, no chevron
`380dp`-`600dp`: centered format bar, no chevron
`600dp+`: tablet format bar (landscape mode on phablets)

**Comment by aforcier** [comment]
Update: made the changes outlined above. Screens `380dp` and over now get a centered format bar (with the HTML button still on the right corner, however).

Screens that are only over `600dp` in landscape mode now get the tablet format bar in that mode (before we only showed it for min-width `600dp`).

Here's the Nexus 4 in portrait:

199-nexus4-portrait-centered

Nexus 4 in landscape:

199-nexus4-landscape-centered

Samsung S3 in landscape (qualifies for tablet-sized format bar):

199-samsung-s3-landscape-keyboard

**Comment by aforcier** [comment]
Ready for another look @bummytime.

**Comment by bummytime** [comment]
Tested on:
- API 16 :+1: 
- API 17 :+1:  (including Nexus4 device)
- API 18 :+1: 
- API 19 :+1: 
- API 21 :+1:
- API 22 :+1:  (including Samsung S6 and Nexus7 devices)

:shipit:

**Pull request merged**
